from datetime import datetime, timezone
from typing import Optional, List, Dict, Any
from uuid import uuid4
from pydantic import BaseModel, Field, ConfigDict
from app.models.telemetry import TelemetryEvent


class ObservationEvent(BaseModel):
    """
    Lightweight wrapper around TelemetryEvent for continuous background processing.
    Tracks execution latency, app context, and success signals.
    """
    observation_id: str = Field(default_factory=lambda: str(uuid4()), description="Unique observation ID")
    telemetry_event: TelemetryEvent = Field(..., description="Captured TelemetryEvent reference")
    app_title: str = Field(default="Unknown Application", description="Active application title")
    latency_ms: float = Field(default=0.0, ge=0.0, description="Execution/interaction latency in ms")
    success_signal: bool = Field(default=True, description="Success signal of the interaction")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Observation timestamp")

    model_config = ConfigDict(use_enum_values=True)


class WorkflowCandidate(BaseModel):
    """
    Discovered workflow candidate generated by continuous pattern matching.
    """
    candidate_id: str = Field(default_factory=lambda: str(uuid4()), description="Unique candidate ID")
    name: str = Field(..., description="Discovered workflow candidate name (e.g. 'Product Search Flow')")
    observed_steps: List[str] = Field(default_factory=list, description="Ordered action step descriptions")
    sequence_event_ids: List[str] = Field(default_factory=list, description="Traceability IDs of telemetry events")
    sequence: List[Any] = Field(default_factory=list, description="Sequence of TelemetryEvents or ObservationEvents")
    
    occurrence_count: int = Field(default=1, ge=1, description="Number of times pattern was observed")
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0, description="Pattern repetition confidence score (0.0 to 1.0)")
    success_rate: float = Field(default=1.0, ge=0.0, le=1.0, description="Observed success rate (0.0 to 1.0)")
    
    applications_involved: List[str] = Field(default_factory=list, description="Unique applications involved")
    discovered_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Discovery timestamp")

    model_config = ConfigDict(use_enum_values=True)


class ObserverNotification(BaseModel):
    """
    Structured notification pushed by the continuous observer when new workflow candidates,
    pattern significance milestones, or stream anomalies occur.
    """
    notification_id: str = Field(default_factory=lambda: str(uuid4()), description="Unique notification ID")
    notification_type: str = Field(
        default="CANDIDATE_DISCOVERED",
        description="Type ('CANDIDATE_DISCOVERED', 'PATTERN_MILESTONE', 'ANOMALY_DETECTED', 'STREAM_HEALTH')"
    )
    title: str = Field(..., description="Notification title")
    message: str = Field(..., description="Detailed notification message")
    candidate_id: Optional[str] = Field(default=None, description="Associated WorkflowCandidate ID if applicable")
    severity: str = Field(default="INFO", description="Severity level ('INFO', 'SUCCESS', 'WARNING', 'ERROR')")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Timestamp")

    model_config = ConfigDict(use_enum_values=True)
